version: '3'
services: 
  mongodb:
    # image: mongo:5.0.2
    image: mongo
    # restart: always 
    env_file: ./.env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes: 
      - mongo_vol:/data/db 
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1  --loglevel warning
    volumes: 
      - redis_vol:/data 
    networks:
    - app-network

  identityaccess:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongodb
    volumes: 
      - /app/node_modules
      - .:/app 
    ports: 
      - "8080:8080"
    command: npm run dev
    networks:
      - app-network

      
volumes: 
  mongo_vol: 
    driver: local
  redis_vol:
    driver: local
  

networks:
  app-network:
    driver: bridge
