version: '3'
services: 
  mongodb:
    image: mongo
    env_file: ./.env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes: 
      - mongo_vol:/data/db 
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes: 
      - redis_vol:/data 
    networks:
    - app-network

  identityaccess:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongodb
    volumes: 
      - /app/node_modules
      - .:/app 
    ports: 
      - "8080:8080"
    command: npm run dev
    networks:
      - app-network

      
volumes: 
  mongo_vol: 
    driver: local
  redis_vol:
    driver: local
  

networks:
  app-network:
    driver: bridge
